/**
 * deploy.local edge — the data plane.
 *
 * Owns everything that must survive a control-plane crash: TLS termination
 * (HTTP/2 on 443 with h1 fallback, plain HTTP on 80), the reverse-proxy hot
 * path for `<app>.local`, WebSocket tunneling, TCP proxies for extra ports,
 * mDNS, and request logging. Dashboard/API traffic forwards to the control
 * plane on 127.0.0.1:7843; when control is down the edge serves a
 * restarting page and apps keep working.
 *
 * State: the deployments table (read-only connection, never migrations) plus
 * IPC hints on `.deploy-data/edge.sock`. Certificates are generated by the
 * control plane; the edge hot-reloads them on `cert:reload`.
 */

import {
  createServer,
  type IncomingMessage,
  type ServerResponse,
  request as httpRequest,
  Agent,
} from 'node:http';
import { createSecureServer as createHttp2Server } from 'node:http2';
import { existsSync } from 'node:fs';
import { setTimeout as sleep } from 'node:timers/promises';
import { installCrashGuard } from '../crash-guard.ts';
import { getTlsOptions, getCaCertBuffer, certsExist } from '../certs.ts';
import { controlRestartingPage } from '../error-page.ts';
import { createHotPathHandler } from './proxy.ts';
import { initEdgeRuntime, getDefaultDbFile } from './runtime.ts';
import { startEdgeIpcServer, getEdgeSockPath } from '../ipc.ts';
import { purgeDeploymentCache } from './response-cache.ts';
import { logRequest, flushRequestLogs } from '../request-log.ts';
import { isAppHost, tunnelUpgrade } from './upgrade-proxy.ts';

installCrashGuard();

const HTTP_PORT = parseInt(process.env.PORT || '80', 10);
const HTTPS_PORT = parseInt(process.env.HTTPS_PORT || '443', 10);
const CONTROL_PORT = parseInt(process.env.CONTROL_PORT || '7843', 10);

// ── Control-plane forwarding ────────────────────────────────────────────────
// Simple pipe proxy for dashboard/API traffic. Distinct from the app hot path:
// no request logging, and failures render the control-restarting page (apps
// are unaffected; only the dashboard is briefly down).

const controlAgent = new Agent({ keepAlive: true, maxSockets: 64 });

// A control-plane restart takes well under a second (supervisor backoff
// starts at 250ms) plus a few seconds of boot. Retrying idempotent requests
// across that window makes restarts invisible to the dashboard — instead of
// a flash of 503s (which, for hashed asset URLs, the browser surfaces as
// module MIME errors), in-flight page loads just stall briefly.
const CONTROL_RETRY_WINDOW_MS = 8_000;
const CONTROL_RETRY_DELAY_MS = 250;

function forwardToControl(
  req: IncomingMessage,
  res: ServerResponse,
  deadline = Date.now() + CONTROL_RETRY_WINDOW_MS,
  // Captured BEFORE stripping pseudo-headers (and threaded through retries):
  // on HTTP/2 compat requests req.url/req.method are getters backed by
  // headers[':path']/[':method'] — once those are deleted, req.url silently
  // becomes undefined and every request forwards as "GET /" (the dashboard's
  // assets all came back as the home page HTML).
  path = req.url || '/',
  method = req.method || 'GET',
) {
  const headers = req.headers;
  for (const key in headers) {
    if (key.charCodeAt(0) === 58 /* ':' */) delete headers[key];
  }
  const proxyReq = httpRequest(
    {
      agent: controlAgent,
      hostname: '127.0.0.1',
      port: CONTROL_PORT,
      path,
      method,
      headers,
    },
    (proxyRes) => {
      const h = proxyRes.headers;
      delete h.connection;
      delete h['keep-alive'];
      delete h['transfer-encoding'];
      delete h.upgrade;
      res.writeHead(proxyRes.statusCode!, h);
      proxyRes.pipe(res);
    },
  );
  proxyReq.on('error', () => {
    if (res.headersSent) {
      res.end();
      return;
    }
    // Only GET/HEAD are safely replayable (a POST body has been consumed).
    if ((method === 'GET' || method === 'HEAD') && Date.now() < deadline) {
      setTimeout(() => forwardToControl(req, res, deadline, path, method), CONTROL_RETRY_DELAY_MS);
      return;
    }
    if (path.startsWith('/api/')) {
      res.writeHead(503, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' });
      res.end(JSON.stringify({ error: 'control plane restarting' }));
    } else {
      controlRestartingPage(res);
    }
  });
  req.pipe(proxyReq);
}

function serveCaCert(res: ServerResponse) {
  const caCert = getCaCertBuffer();
  res.writeHead(200, {
    'Content-Type': 'application/x-x509-ca-cert',
    'Content-Disposition': 'attachment; filename="deploy-local-ca.crt"',
    'Content-Length': caCert.length,
  });
  res.end(caCert);
}

async function main() {
  // The control plane creates/migrates the DB and generates certs on its
  // first boot. Wait for both — the supervisor starts control first, so this
  // resolves immediately except on a very first install.
  const dbFile = getDefaultDbFile();
  let waitLogged = false;
  while (!existsSync(dbFile) || !certsExist()) {
    if (!waitLogged) {
      console.log('[edge] waiting for control plane to initialize DB + certs...');
      waitLogged = true;
    }
    await sleep(2000);
  }

  let httpsServer: ReturnType<typeof createHttp2Server>;

  const ipcServer = startEdgeIpcServer(getEdgeSockPath(), {
    onRouteChanged: (name) => runtime.routes.reconcile(name),
    onCachePurge: (name) => purgeDeploymentCache(name),
    onCertReload: () => reloadTls(),
    onControlConnected: () => {
      runtime.routes.reloadAll();
      reloadTls();
    },
  });

  const runtime = initEdgeRuntime({
    dbFile,
    logRequest,
    emitEvent: (event) => ipcServer.sendEvent(event),
    onCertReload: () => reloadTls(),
  });

  function reloadTls() {
    try {
      const opts = getTlsOptions();
      httpsServer.setSecureContext({ key: opts.key, cert: opts.cert, ca: opts.ca });
      console.log('[edge] TLS context reloaded');
    } catch (err) {
      console.error('[edge] TLS reload failed:', err);
    }
  }

  const hotPath = createHotPathHandler(runtime.hotPathDeps);

  const tlsOpts = getTlsOptions();
  httpsServer = createHttp2Server(
    {
      key: tlsOpts.key,
      cert: tlsOpts.cert,
      ca: tlsOpts.ca,
      allowHTTP1: true,
      // Larger initial window so HTTP/2 streams don't stall waiting for
      // WINDOW_UPDATE during streaming SSR / large asset transfers.
      settings: { initialWindowSize: 1024 * 1024 },
    },
    (rawReq, rawRes) => {
      const req = rawReq as unknown as IncomingMessage;
      const res = rawRes as unknown as ServerResponse;
      if (hotPath(req, res)) return;
      if (req.url === '/ca.crt') {
        serveCaCert(res);
        return;
      }
      forwardToControl(req, res);
    },
  );

  // HTTP server: CA cert + CLI endpoints, API over HTTP (CLI compatibility),
  // browser redirect to HTTPS.
  let actualHttpsPort = HTTPS_PORT;
  const httpServer = createServer((req, res) => {
    if (req.url === '/ca.crt') {
      serveCaCert(res);
      return;
    }
    if (req.url === '/install' || req.url?.startsWith('/cli') || req.url?.startsWith('/api/')) {
      forwardToControl(req, res);
      return;
    }
    const host = req.headers.host?.split(':')[0] || 'deploy.local';
    const portSuffix = actualHttpsPort !== 443 ? `:${actualHttpsPort}` : '';
    res.writeHead(301, { Location: `https://${host}${portSuffix}${req.url}` });
    res.end();
  });

  // Upgrades: app hosts tunnel to the container; dashboard /ws tunnels to the
  // control plane; everything else is destroyed.
  function handleUpgrade(req: IncomingMessage, socket: import('node:stream').Duplex, head: Buffer) {
    const hostHeader = req.headers.host || 'deploy.local';
    const hostname = hostHeader.split(':')[0];
    const deps = { getRoute: runtime.hotPathDeps.getRoute };
    if (isAppHost(hostname, deps)) {
      const route = deps.getRoute(hostname.substring(0, hostname.length - 6));
      const backend = route?.selectBackend?.(req) ?? null;
      const port = backend?.port ?? route?.port;
      if (port) {
        tunnelUpgrade(
          req,
          socket,
          head,
          port,
          backend?.host || route?.backendHost || '127.0.0.1',
          backend?.release,
        );
      } else {
        backend?.release();
        socket.destroy();
      }
      return;
    }
    const pathname = (req.url || '').split('?')[0];
    if (pathname === '/ws') {
      tunnelUpgrade(req, socket, head, CONTROL_PORT);
    } else {
      socket.destroy();
    }
  }
  httpsServer.on('upgrade', handleUpgrade);
  httpServer.on('upgrade', handleUpgrade);

  function shutdown(signal: string) {
    console.log(`\n[edge] ${signal} received, shutting down...`);
    flushRequestLogs();
    runtime.close();
    ipcServer.close();
    httpsServer.close();
    httpServer.close(() => {
      console.log('[edge] stopped');
      process.exit(0);
    });
    setTimeout(() => process.exit(1), 5000).unref();
  }
  process.on('SIGTERM', () => shutdown('SIGTERM'));
  process.on('SIGINT', () => shutdown('SIGINT'));

  httpsServer.on('error', (err: NodeJS.ErrnoException) => {
    if (err.code === 'EADDRINUSE' || err.code === 'EACCES') {
      actualHttpsPort = 8443;
      console.warn(
        `[edge] port ${HTTPS_PORT} unavailable (${err.code}), falling back to ${actualHttpsPort}`,
      );
      httpsServer.listen(actualHttpsPort, () => {
        console.log(`[edge] serving https on :${actualHttpsPort}`);
      });
    } else {
      throw err;
    }
  });

  httpServer.on('error', (err: NodeJS.ErrnoException) => {
    console.warn(`[edge] HTTP server failed to bind port ${HTTP_PORT} (${err.code}) — skipping`);
  });

  httpsServer.listen(HTTPS_PORT, () => {
    console.log(`[edge] serving https on :${HTTPS_PORT}`);
  });
  httpServer.listen(HTTP_PORT, () => {
    console.log(`[edge] serving http on :${HTTP_PORT}`);
  });
}

main().catch((err) => {
  console.error('[edge] failed to start:', err);
  process.exit(1);
});
